---
version: '2'

services:

  jenkins-main:
    image: ibandrea/jenkins:2.32.2
    container_name: jenkins-main
    ports:
      - 8081:8080
      - 50001:50000
    expose:
      - 8080
      - 50000
    volumes:
      - ./data/:/var/jenkins_home/:rw
    networks:
      backend:
        aliases:
          - jenkins-course

  jenkins-slave-1:
    image: ibandrea/jenkins-slave
    ports:
      - "2222:22"
    networks:
      backend:
        aliases:
          - jenkins-slave-1

  jenkins-slave-2:
    image: ibandrea/jenkins-slave
    ports:
      - "2223:22"
    networks:
      backend:
        aliases:
          - jenkins-slave-2

  tomcat:
    image: ibandrea/tomcat
    ports:
      - 8082:8080
    expose:
      - 8080
    networks:
      backend:
        aliases:
          - tomcat

networks:
  backend: {}
